version: 2
jobs:
  build:
    working_directory: ~/angular-cli
    docker:
      - image: angular/ngcontainer
    steps:
      - checkout
      - restore_cache:
          key: angular-cli-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: |
          npm install -g npm@~5.3.0
          npm install
      - save_cache:
          key: angular-cli-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run: xvfb-run -a node tests/run_e2e.js --glob=tests/build/**
